---
title: "Lab 8"
author: "SSalem"
date: "3/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages
```{r}
library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)


```

###Column graph of Texas oil Spills

```{r}
oil_spills<- read_csv("oil_spills.csv")


#allows you to filter what data you need from full df
df <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` < 2017)  %>% 
group_by(`Accident Year`) %>% 
  summarise(Loss = sum(`Net Loss (Barrels)`))

colnames(df)<- c("Year", "Loss")

ggplot(df, aes( x = Year, y = Loss))+
geom_col()


```


### Leaflet plot of spill locations in TX in 2016

```{r}
df_loc<- oil_spills %>% 
  filter(`Accident State`== "TX" & `Accident Year` == 2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)

colnames(df_loc) <- c("latitude", "longitude", "net_loss")

# recognizes it as spatial data
oil_sf <- st_as_sf(df_loc, coords = c("longitude", "latitude"), crs = 4326)
  
leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers()

# interactive map 
  
  
```

